title: "Marvin Jacquet"
description: >-
  
baseurl: ""
url: "https://marvinjacquet.github.io"
og_image: /assets/img/profile-pic.jpg
google_analytics: ""
theme: bay_jekyll_theme

header:
  pages:
    - name: CV
      slug: /cv/en
    - name: Research
      slug: /research/en
    - name: Teaching
      slug: /teaching
    - name: Blog
      slug: /blog

footer:
  show_powered_by: true
  contact:
    - type: email
      name: Email
      value: yourmail@domain.com
  follow:
    - type: researchgate
      name: Researchgate
      link: https://www.researchgate.net/profile/Marvin-Jacquet
    - type: github
      name: GitHub
      link: https://github.com/marvinjacquet/
    - type: orcid
      name: ORCID
      link: https://orcid.org/0000-0002-9890-7908
    - type: linkedin
      name: LinkedIn
      link: https://www.linkedin.com/in/marvin-jacquet-2059a8182/



# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
