title: "Marvin Jacquet - personal website"
description: >-
  
baseurl: ""
url: "https://marvinjacquet.github.io"
og_image: /assets/img/profile-pic.jpg
google_analytics: ""
remote_theme: eliottvincent/bay@v1.2.5

header:
  pages:
    - name: CV
      slug: /cv
    - name: Publications
      slug: /publications
    - name: Congres
      slug: /congres
    - name: Enseignement
      slug: /enseignement
    - name: Blog
      slug: /blog

footer:
  show_powered_by: true
  contact:
    - type: email
      name: Email
      value: yourmail@domain.com
  follow:
    - type: linkedin
      name: LinkedIn
      link: https://www.linkedin.com/in/marvin-jacquet-2059a8182/
    - type: github
      name: GitHub
      link: https://github.com/marvinjacquet/
    - name: ORCID
      link: https://orcid.org/0000-0002-9890-7908
    - name: RGate
      link: https://www.researchgate.net/profile/Marvin-Jacquet

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
